mongo:
  image: mongo:3.6.0
  ports:
    - "27017:27017"
  command: mongod --noauth
#  environment:
#    MONGODB_USER: "${db_user_env}"
#    MONGODB_DATABASE: "${dbname_env}"
#    MONGODB_PASS: "${db_pass}"
